config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'pages#explore'

  get 'explorer', to: 'pages#explore', as: :explore
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  post 'sign_out', to: 'sessions#destroy', as: :sign_out

  resources :users, only: [:show] do
    member do
      post 'remove_skill'
      post 'add_skill'
      post 'set_rate'
      post 'edit_bio'

      get 'calendar'
      post 'mark_calendar'
    end
  end

  resources :events, only: [:new, :create] do
    member do
      post 'join'
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_taggable_on :skills

  has_many :segments
  has_many :events
  has_many :participations

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |u|
      u.provider = auth.provider
      u.uid = auth.uid
      u.name = auth.info.name
      u.avatar_url = auth.info.image
      u.oauth_token = auth.credentials.token
      u.oauth_token_expires_at = Time.at(auth.credentials.expires_at)

      u.save!
    end
  end

  def has_joined?(event)
    self.participations.where(event: event).any?
  end

  def join!(event)
    self.participations.create!(event: event)
  end

  def total_tutor_hours
    0.5 * self.segments.where('owner_id != ?', self.id).map { |s| (s.ed - s.st + 1) }.sum
  end

  private
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :fetch_user

  def show
    @week_offset = params[:week_offset].to_i

    if signed_in?
      givings = Segment.where(user_id: current_user.id).where('owner_id != ?', current_user.id)
      receivings = Segment.where('user_id != ?', current_user.id).where(owner_id: current_user.id)

      @tutorings = givings.map { |s| [:giving, s] } + receivings.map { |s| [:receiving, s] }
      @tutorings = @tutorings.sort_by { |t| [t[1].date, t[1].st, t[1].ed] }
    end
  end

  def remove_skill
    return redirect_to root_path, flash: {error: "You can only edit your own profile. "} unless current_user == @user

    skill = params[:skill]

    @user.skill_list.remove(skill)
    @user.save!

    redirect_to @user, flash: {success: "You have successfully removed the skill \"#{skill}\". "}
  end

  def add_skill
    return redirect_to root_path, flash: {error: "You can only edit your own profile. "} unless current_user == @user

    skill = params[:skill]

    @user.skill_list.add(skill)
    @user.save!

    redirect_to @user, flash: {success: "You have successfully added the skill \"#{skill}\" to your profile. "}
  end

  def set_rate
    return redirect_to root_path, flash: {error: "You can only set your own rate. "} unless current_user == @user

    @user.rate = params[:rate].to_f
    @user.save!

    redirect_to @user, flash: {success: "You have successfully set your rate to %0.1f tokens per hour. " % @user.rate}
  end

  def edit_bio
    return redirect_to root_path, flash: {error: "You can only edit your own bio. "} unless current_user == @user

    @user.bio = params[:bio]
    @user.save!

    redirect_to @user, flash: {success: "You have successfully edited your bio. "}
  end

  def mark_calendar
    return redirect_to root_path, flash: {error: "You need to be signed in. "} unless signed_in?

    date = Date.parse(params[:date])
    st = params[:st].to_i
    ed = params[:ed].to_i
    action = params[:mark_as]

    st, ed = ed, st if st > ed

    case action
    when 'reserved'
      return redirect_to @user, flash: {error: "You shouldn't reserve your own time slots. "} if @user.id == current_user.id

      price = @user.rate * 0.5 * (ed - st + 1)
      return redirect_to @user, flash: {error: "You don't have enough tokens left to reserve this slot. "} if current_user.balance <= price

      return redirect_to @user, flash: {error: "Cannot reserve slots. "} unless Segment.insert(@user, current_user, date, st, ed)

      current_user.balance -= price
      current_user.save!
      @user.balance += price
      @user.save!

      return redirect_to @user, flash: {success: "You have successfully reserved the slots! "}
    when 'available'
      return redirect_to @user, flash: {error: "You can only mark your own time slots available. "} unless @user.id == current_user.id
      return redirect_to @user, flash: {error: "Cannot mark slots as available. "} unless Segment.insert(@user, current_user, date, st, ed)
      return redirect_to @user, flash: {success: "You have successfully marked the slots as available! "}
    when 'unavailable'
      return redirect_to @user, flash: {error: "You can only mark your own time slots unavailable. "} unless @user.id == current_user.id
      return redirect_to @user, flash: {error: "Cannot mark slots as unavailable. "} unless Segment.remove(@user, current_user, date, st, ed)
      return redirect_to @user, flash: {success: "You have successfully marked the slots as unavailable! "}
    end

    raise "Unexpected action: #{action}. "
  end

  private
    def slot_start(day, slot)
      day.in_time_zone + (slot * 30).minutes
    end

    def slot_center(day, slot)
      slot_start(day, slot) + 15.minutes
    end

    def slot_end(day, slot)
      slot_start(day, slot). + 30.minutes
    end

    def fetch_user
      @user = User.find(params[:id])
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_calendar.html.haml
- today = Date.today
- center = today + week_offset * 7

- st = center.at_beginning_of_week
- ed = center.at_end_of_week

- slots = {}
- (st..ed).each { |d| slots[d] = Segment.get_slots(user, d) }

- if own
  %p.instruction Select slots to toggle your availability. Slots with white background are your current available time slots. Slots with green background are already reserved by students.
- else
  %p.instruction Select slots to reserve for private tutoring. Slots with white background are current available time slots. Slots with green background are already reserved by other students.

= link_to 'Prev Week', user_path(user, week_offset: week_offset - 1), class: 'prev'
= link_to 'Next Week', user_path(user, week_offset: week_offset + 1), class: 'next'

%p.current= "#{st.strftime("%Y/%m/%d")} - #{ed.strftime("%Y/%m/%d")}"

%table.calendar{'data-own' => own.to_s, 'data-rate' => user.rate}
  %tr
    %th
    - (st..ed).each do |d|
      %th= d.strftime("%m/%d")
  - 0.upto(47) do |i|
    - hour = i / 2
    - on_hour = (i % 2 == 0)
    - text = on_hour ? "#{(hour - 1) % 12 + 1} #{hour >= 12 ? "PM" : "AM"}" : ""
    %tr
      %th=  text
      - (st..ed).each do |d|
        %td{'class' => slots[d][i].to_s, 'data-date' => d.to_s, 'data-slot' => i, 'data-status' => slots[d][i].to_s} &nbsp;

= form_tag mark_calendar_user_path(user), id: 'mark_calendar_form' do |f|
  = hidden_field_tag :date
  = hidden_field_tag :st
  = hidden_field_tag :ed
  = hidden_field_tag :mark_as

app/views/users/show.html.haml
- own = (current_user == @user)
- tutor = @user.rate.present?

.container
  .left
    .container
      = image_tag @user.avatar_url, class: 'avatar'
      .info
        %h2= @user.name

        %p.skills
          - if @user.skill_list.empty?
            - if own
              %span You haven't put in any skill yet.
            - else
              %span This user hasn't put in any skill yet.
          - else
            - @user.skill_list.each do |s|
              %span.skill
                = s
                - if own
                  = link_to remove_skill_user_path(@user, skill: s), method: :post, data: {confirm: "Do you really want to remove the skill \"#{s}\" from your profile? "} do
                    %i.fa.fa-trash-o

        - if own
          = link_to 'Add a Skill', add_skill_user_path(@user, skill: 'PLACEHOLDER'), class: 'action add-skill', method: :post
          = link_to "#{tutor ? 'Change' : 'Set'} Private Tutoring Rate", set_rate_user_path(@user, rate: 'PLACEHOLDER'), class: 'action set-rate', method: :post

        .scoreboard
          %p.stat
            Taught for
            %span.score= @user.total_tutor_hours
            hours
          %p.stat
            Held
            %span.score= @user.events.count
            events
          - if tutor
            %p.stat
              Private tutoring
              %span.score= "%0.1f" % @user.rate
              tokens per hour

          - if own
            %p.stat
              I have
              %span.score= "%0.1f" % @user.balance
              tokens left

    .container
      %p.bio
        %span.content
          = "#{@user.bio.presence || "This user has written nothing at all. "}"
        - if own
          = link_to 'Edit My Bio', '#', class: 'edit-bio'
      = form_tag edit_bio_user_path(@user), id: 'edit_bio_form' do |f|
        = hidden_field_tag :bio

    - if own
      .container
        %h3 Scheduled Private Tutoring
        - @tutorings.each do |t|
          - type, seg = t

          - verb = type.to_s.capitalize
          - prep = (type == :giving ? 'to' : 'from')
          - other = (type == :giving ? seg.owner : seg.user)

          %p.tutoring
            = verb
            tutoring
            = prep
            %span.key= other.name
            on
            %span.key= date_str(seg.date) + " (#{slot_start_to_text(seg.st)} - #{slot_end_to_text(seg.ed)})"

    .container.events
      %h3 Events Hosted
      - if own
        = link_to 'Host New Event', new_event_path, class: 'action'

      - if @user.events.empty?
        %p.instruction= "#{own ? "You haven't" : "This user hasn't"} hosted any event yet."
      - else
        - @user.events.each do |e|
          = render e


  .right
    .container
      %h3 Private Tutoring Availability
      - if tutor
        = render 'calendar', user: @user, own: own, week_offset: @week_offset
      - else
        - if own
          %p.instruction Set a private tutor rate on the left to enable private tutoring.
        - else
          %p.instruction This tutor does not provide private tutoring yet.