config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'pages#explore'

  get 'explorer', to: 'pages#explore', as: :explore
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  post 'sign_out', to: 'sessions#destroy', as: :sign_out

  resources :users, only: [:show] do
    member do
      post 'remove_skill'
      post 'add_skill'
      post 'set_rate'
      post 'edit_bio'

      get 'calendar'
      post 'mark_calendar'
    end
  end

  resources :events, only: [:new, :create] do
    member do
      post 'join'
    end
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  default_scope -> { order('start_time ASC')}

  belongs_to :user
  has_many :participations

  validates :title, presence: true, length: {minimum: 1, maximum: 200}
  validates :description, presence: true, length: {minimum: 10, maximum: 2000}
  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :rate, presence: true, numericality: {minimum: 0.5}

  validates :date, presence: true

  before_validation :set_dates

  acts_as_taggable_on :skills

  def date
    @date ||= start_time.try(:to_date)
  end

  def start_minute
    return 0 if (@start_minute.nil? && start_time.nil?)
    @start_minute ||= ((start_time - date.in_time_zone) / 60).to_i
  end

  def end_minute
    return 0 if (@end_minute.nil? && end_time.nil?)
    @end_minute ||= ((end_time - date.in_time_zone) / 60).to_i
  end

  def date=(date)
    begin
      @date = date.to_date
    rescue ArgumentError
      @date = nil
    end
  end

  def start_minute=(min)
    @start_minute = min.to_i
  end

  def end_minute=(min)
    @end_minute = min.to_i
  end

  def same_day?
    self.start_time.to_date == self.end_time.to_date
  end

  def location_is_url?
    self.location =~ /^http/
  end

  private
    def set_dates
      return if date.nil?
      self.end_minute += 60 * 24 if self.end_minute <= self.start_minute

      self.start_time = date + start_minute.minutes
      self.end_time = date + end_minute.minutes
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.user = current_user

    if @event.save
      current_user.join!(@event)
      redirect_to current_user, flash: {success: "You have successfully created the event \"#{@event.title}\". "}
    else
      render 'new'
    end
  end

  def join
    return redirect_to root_path, flash: {error: 'You have to be signed in. '} unless signed_in?

    event = Event.find(params[:id])

    return redirect_to event.user, flash: {error: "You don't have enough tokens left. "} unless current_user.balance >= event.rate

    current_user.balance -= event.rate
    current_user.save!
    event.user.balance += event.rate
    event.user.save!

    current_user.join!(event)

    return redirect_to event.user, flash: {success: "You have successfully joined the event. "}
  end

  private
    def event_params
      params.require(:event).permit(:title, :description, :location, :date, :start_minute, :end_minute, :rate, :skill_list)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.haml
.event
  - if !current_user.try(:has_joined?, event)
    = link_to 'Join', join_event_path(event), method: :post, class: 'join', data: {confirm: "Join this event for #{event.rate} tokens. You sure? "}
  %p.title= event.title + (current_user.try(:has_joined?, event) ? " (You are Participating)" : " (#{event.rate} tokens)")
  %p.details
    - if event.same_day?
      = "#{date_str(event.start_time)} #{time_str(event.start_time)} - #{time_str(event.end_time)}"
    - else
      = "#{date_str(event.start_time)} #{time_str(event.start_time)} - #{date_str(event.end_time)} #{time_str(event.end_time)}"
    at
    - if event.location_is_url?
      = link_to event.location, event.location
    - else
      = event.location
  %p.tags
    - event.skill_list.each do |s|
      %span.tag= s
  %p.description= event.description

app/views/events/create.html.haml
%h1 Events#create
%p Find me in app/views/events/create.html.haml

app/views/events/new.html.haml
%h1 Host New Event

- if @event.errors.any?
  %div.errors
    - @event.errors.full_messages.each do |m|
      %p= m

= form_for @event, html: {class: 'centre-form'} do |f|
  = f.text_field :title, placeholder: 'Title of the event. '
  = f.text_area :description, placeholder: 'Detailed description of the event. '
  = f.text_field :location, placeholder: 'Location of the event (physical location or webcast URL). '
  = f.text_field :date, placeholder: 'Date of the event (e.g. 2016/09/13). '
  = f.select :start_minute, minute_select_options('Starts at ')
  = f.select :end_minute, minute_select_options('Ends at ')
  = f.text_field :rate, placeholder: 'Price of the event in tokens. '
  = f.text_field :skill_list, placeholder: 'Comma seperated list of skill tags. '

  = f.submit "Create Event"