config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'pages#explore'

  get 'explorer', to: 'pages#explore', as: :explore
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  post 'sign_out', to: 'sessions#destroy', as: :sign_out

  resources :users, only: [:show] do
    member do
      post 'remove_skill'
      post 'add_skill'
      post 'set_rate'
      post 'edit_bio'

      get 'calendar'
      post 'mark_calendar'
    end
  end

  resources :events, only: [:new, :create] do
    member do
      post 'join'
    end
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title UMentor
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body{class: "#{controller_name}_action", id: "#{controller_name}_#{action_name}"}
    %header
      .container
        %span.brand UMentor
        %nav
          %ul
            - if signed_in?
              %li= "Welcome, #{current_user.name} (%0.1f tokens left)" % current_user.balance
              %li= link_to 'Sign Out', sign_out_path, method: :post
            - else
              %li= link_to 'Sign In', "/auth/google_oauth2"
            %li= link_to 'Explore', explore_path
            - if signed_in?
              %li= link_to 'Profile', user_path(current_user)
    .container
      - [:success, :error].each do |t|
        - if flash[t].present?
          = content_tag :div, flash[t], class: "flash #{t.to_s}"
    .container
      = yield

    %footer
      .container
        %p Made with Love, UMentor 2016